CREATE USER "ATGCORE" PROFILE "DEFAULT" IDENTIFIED BY "ATGCORE"
ACCOUNT UNLOCK
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON USERS;
GRANT "CONNECT" TO "ATGCORE" WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "ATGCORE" WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "ATGCORE" WITH ADMIN OPTION;
GRANT "DBA" TO "ATGCORE" WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO "ATGCORE" WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO "ATGCORE" WITH ADMIN OPTION;


CREATE USER "ATGCATALOGA" PROFILE "DEFAULT" IDENTIFIED BY "ATGCATALOGA"
ACCOUNT UNLOCK
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON USERS;
GRANT "CONNECT" TO "ATGCATALOGA" WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "ATGCATALOGA" WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "ATGCATALOGA" WITH ADMIN OPTION;
GRANT "DBA" TO "ATGCATALOGA" WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO "ATGCATALOGA" WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO "ATGCATALOGA" WITH ADMIN OPTION;


CREATE USER "ATGCATALOGB" PROFILE "DEFAULT" IDENTIFIED BY "ATGCATALOGB"
ACCOUNT UNLOCK
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON USERS;
GRANT "CONNECT" TO "ATGCATALOGB" WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "ATGCATALOGB" WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "ATGCATALOGB" WITH ADMIN OPTION;
GRANT "DBA" TO "ATGCATALOGB" WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO "ATGCATALOGB" WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO "ATGCATALOGB" WITH ADMIN OPTION;


CREATE USER "ATGPUBCORE" PROFILE "DEFAULT" IDENTIFIED BY "ATGPUBCORE"
ACCOUNT UNLOCK
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON USERS;
GRANT "CONNECT" TO "ATGPUBCORE" WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "ATGPUBCORE" WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "ATGPUBCORE" WITH ADMIN OPTION;
GRANT "DBA" TO "ATGPUBCORE" WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO "ATGPUBCORE" WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO "ATGPUBCORE" WITH ADMIN OPTION;